### ISSUE TITLE
光标在行内代码中不显示

### ISSUE THREAD

**Issue by Tlonglan** [UserZYF/zhang-light#10]
https://user-images.githubusercontent.com/38731172/158067375-9665ac7c-1e40-4e76-b864-d61ea347461e.mp4

> 版本：0.5

请问这是特性吗？
感觉在行内代码中看不见光标的位置有点不方便噢……

**Comment by UserZYF** [comment]
感谢反馈，是个bug，下个版本修复

**Comment by bahayonghang** [comment]
行内公式也会出现类似的情况，行内公式后光标不显示 @UserZYF

**Comment by UserZYF** [comment]
下午更新
