### ISSUE TITLE
纵向排列的两个超级块被选中时样式不太明显

### ISSUE THREAD

**Issue by Tlonglan** [UserZYF/zhang-light#11]
https://user-images.githubusercontent.com/38731172/158067589-dfbfc242-7d4f-4a10-a5b0-31caa84d4412.mp4

> 版本：0.5

纵向排列的两个超级块选中后样式不太明显。。。希望可以优化一下下

**Comment by UserZYF** [comment]
感谢反馈，下个版本尝试修复一下
