### ISSUE TITLE
#优化建议#

### ISSUE THREAD

**Issue by Faith-YSQ** [UserZYF/zhang-light#13]
1、在思源联系页面链接悬停预览里，自动编号并没有被去除，而相联系的页面已经去除了编号。
2、导出PDF中自动编号仍然存在

https://user-images.githubusercontent.com/66512309/159270640-e17148b3-c192-4e68-910f-94774eeab8be.mp4

。

**Comment by UserZYF** [comment]
感谢反馈，如果想要彻底去掉自动编号，删除style文件下的auto-number.css文件，再重启思源笔记即可。我这里试了一下，删除后预览也是没有自动编号的。猜测你是用了文档的自定义属性，如果想要彻底去除，可以试试上面的方法，集市最下面有介绍
