### ISSUE TITLE
建议优化一下页面标签栏的配色

### ISSUE THREAD

**Issue by o-ut-man** [UserZYF/zhang-light#15]
![image](https://user-images.githubusercontent.com/34265164/159843297-a240547a-be20-4b45-a0b9-54fe42d1e738.png)
现在这种配色，在标签栏只有2个的情况下，不容易辨识哪个是当前选中的。

**Comment by UserZYF** [comment]
不好意思，刚回复，后续会参考ipad上的软件格式或者sarfari浏览器的样式，对标签页进行优化，感谢反馈
