### ISSUE TITLE
行内代码块吞光标

### ISSUE THREAD

**Issue by Soywei00** [UserZYF/zhang-light#16]
[视频见评论](https://ld246.com/article/1648174108545/comment/1648174819570#comments)
目前测试行内代码块是有丢失光标的，而且是肯定出现，默认和其他主题没有这种情况，希望修复。

**Comment by UserZYF** [comment]
请问是否在集市中更新到了最新版，在上个版本中已经修复了这个bug,dark版本随后更新，感谢提议
