### ISSUE TITLE
希望无序列表转换表格后，表格可以手动调整宽度

### ISSUE THREAD

**Issue by 1995hanjian** [UserZYF/zhang-light#18]
如题所述，或者像表格的自动宽度功能也行
出现第二行就一个字的情况实在有点逼死强迫症

多谢多谢！

**Comment by 1995hanjian** [comment]
![image](https://user-images.githubusercontent.com/39188734/160213250-1f2e2207-7a0d-48ed-af5b-8198b4c42c86.png)

**Comment by UserZYF** [comment]
在style文件夹的custom-function-for-blocks.css文件中，搜索列表转化为表格，找到下面的代码，将120修改为150试试。
这个实质上是修改CSS外观，不是实际上的表格，所以不具有手动调整宽度的功能。
另外，也可以试试dark+主题，也具有这个功能（type=table），但是具体细节不一样，你可以试试效果。
下一次更新，我会增加默认表格宽度的
`/* ————————————————————对符号后文字设置格式———————————————————— */
.protyle-wysiwyg *[custom-f="bg"] .p {
    flex: 1;
    text-align: left;
    align-items: center;
    display: flex;
    min-width: 120px;
    height: auto;
    margin: 0;
    text-align: justify;
}`

**Comment by 1995hanjian** [comment]
> 在style文件夹的custom-function-for-blocks.css文件中，搜索列表转化为表格，找到下面的代码，将120修改为150试试。 这个实质上是修改CSS外观，不是实际上的表格，所以不具有手动调整宽度的功能。 另外，也可以试试dark+主题，也具有这个功能（type=table），但是具体细节不一样，你可以试试效果。 下一次更新，我会增加默认表格宽度的 `/* ————————————————————对符号后文字设置格式———————————————————— */ .protyle-wysiwyg *[custom-f="bg"] .p { flex: 1; text-align: left; align-items: center; display: flex; min-width: 120px; height: auto; margin: 0; text-align: justify; }`

好的嗷，多谢多谢
