### ISSUE TITLE
建议优化一下标题折叠样式

### ISSUE THREAD

**Issue by o-ut-man** [UserZYF/zhang-light#25]
折叠是为了收起子项的内容，而不是说这个标题不重要，所以不该用淡化的样式。
建议不需要处理标题本身的样式，只需要增加折叠标记就可以了。 就像现在的列表折叠一样

当前的标题折叠样式
![image](https://user-images.githubusercontent.com/34265164/161373249-650ffd4b-0b3b-419a-b8a9-15d44b48e424.png)
![image](https://user-images.githubusercontent.com/34265164/161373252-f1829642-7222-49d6-afe3-bb0f0485e05f.png)

当前的列表折叠样式
<img width="186" alt="Snipaste_2022-04-02_16-28-28" src="https://user-images.githubusercontent.com/34265164/161374525-1924ca0e-cd7e-495c-9b82-8277a97fa359.png">

**Comment by UserZYF** [comment]
感谢反馈，因为标题折叠后，连着底部的各种子标题和内容都折叠了起来，如果只是给标题增加标题，如在左上角添加图标或者图形，或者是增加标题透明度，体现不出这种感觉，而且容易忽略。
故参考`notion-theme`主题，做了如此处理。
等积累一定量的用户反馈，之后再看是否需要改进标题折叠效果😄
