### ISSUE TITLE
行内批注没有生效

### ISSUE THREAD

**Issue by Soywei00** [UserZYF/zhang-light#26]
![image](https://user-images.githubusercontent.com/16738821/161376441-ca2b6b59-552d-42c7-8521-d4fab7611c1a.png)
版本号：1.9.6
系统：windows

**Comment by UserZYF** [comment]
重启一下思源笔记试试

**Comment by Soywei00** [comment]
> 重启一下思源笔记试试

我卸载重装了主题，重启电脑之后还是没生效。
