### ISSUE TITLE
希望减小一下左右排版的搜索框的大小

### ISSUE THREAD

**Issue by Tlonglan** [UserZYF/zhang-light#27]
左右排版的搜索框真的很香！感谢大佬支持这个功能！！❤
如果可以稍微减少一下整个视觉上的占比就更好了~ 
> 一打开还感觉有点怪怪的，对比一下原生的弹窗，确实大太多了，视线要在整个屏幕上不停的转移，有点累人说实话。。。

![image](https://user-images.githubusercontent.com/38731172/161433013-897ca372-c803-4460-8c52-66f4942cd73d.png)

![image](https://user-images.githubusercontent.com/38731172/161433089-d52b1ff0-4c23-4f03-80bc-49518488165f.png)

**Comment by UserZYF** [comment]
ok，我跟原作者联系一下，看能不能支持缩小一下窗口

**Comment by Tlonglan** [comment]
好的。辛苦啦~

**Comment by UserZYF** [comment]
下次更新加上
![Snipaste_2022-04-04_10-34-00](https://user-images.githubusercontent.com/38289979/161466682-94fc7c77-1f1b-4d10-8b79-6e8cb35e003e.png)
![Snipaste_2022-04-04_10-34-12](https://user-images.githubusercontent.com/38289979/161466694-e41f8e7d-5233-420f-80c6-e948fd8fb943.png)

**Comment by Tlonglan** [comment]
好耶
