### ISSUE TITLE
使用主题后，集市的其他主题偶尔会缺少“使用按钮”

### ISSUE THREAD

**Issue by Tlonglan** [UserZYF/zhang-light#28]
暗色主题和亮色主题都有这个问题，偶尔触发
![image](https://user-images.githubusercontent.com/38731172/161433335-5fbac62b-0eba-4884-af4f-7d576ca7ff0e.png)

**Comment by UserZYF** [comment]
正在使用的主题不会显示使用按钮。（猜测你白天使用主题zhang-light，晚上使用dark+，你可以更换这两个主题看看效果）

**Comment by Tlonglan** [comment]
原来如此~ 那没事了:smile:
