### ISSUE TITLE
章节标题

### ISSUE THREAD

**Issue by bahayonghang** [UserZYF/zhang-light#3]
不知道能否有一个去掉第一章、第一节这种标题前置的版本，个人感觉这种prefix反而会影响笔记的阅读（个人观点）
感谢作者维护了这么耐看的主题

**Comment by UserZYF** [comment]
感谢使用主题，不知道您指的是不是希望去掉自动编号。
下个版本默认去掉自动编号，不过可以通过对文档的自定义属性开启。请关注下个版本的更新，具体的说明会在READ.ME文档中进行详细说明。

**Comment by bahayonghang** [comment]
> 感谢使用主题，不知道您指的是不是希望去掉自动编号。 下个版本默认去掉自动编号，不过可以通过对文档的自定义属性开启。请关注下个版本的更新，具体的说明会在READ.ME文档中进行详细说明。

感谢作者的回复，希望这个主题能走的更远
