### ISSUE TITLE
引用搜索框在切到别处时没有及时消失

### ISSUE THREAD

**Issue by Tlonglan** [UserZYF/zhang-light#31]
![image](https://user-images.githubusercontent.com/38731172/162583872-1313d296-27aa-4fde-b58a-d5f2a8a43079.png)
--- 
![image](https://user-images.githubusercontent.com/38731172/162583873-23c5f55e-77ef-41ba-a4f0-de8f4cbbe37f.png)

- 在引用的时候临时切到其他文档上，再切回来发现这个搜索待选项还在
    - 在本文档内滚动浏览时也不会消失，有点阻碍视线了
- 而且思源有个特性，切换到另一篇文档时，会回到文档开头，这样整个待选项的存在会显得很突兀
- 希望可以在失去焦点的时候关掉这个待选项，即使后面需要重新敲搜索关键词。比起这种强烈的突兀感，这一点小操作应该也不算什么了

**Comment by UserZYF** [comment]
这个最好在社区或者siyuan的GitHub上反馈一下，这个D大应该能解决

**Comment by Tlonglan** [comment]
好~
