### ISSUE TITLE
【建议】字体的标点符号使用

### ISSUE THREAD

**Issue by jinghu-moon** [UserZYF/zhang-light#36]
你觉得霞鹜文楷的符号搭配仓耳今楷的文字怎么样？我觉得仓耳今楷的中英文符号对比不明显。中文符号与前后文字的间隔太小。

![](https://s3.bmp.ovh/imgs/2022/04/14/26850b00fde58308.png)

如果你想换的换。可以试试 [fontmin](https://github.com/ecomfe/fontmin-app)（一个字体子集化的软件）。

font 属性这样写：font-family: "LXGWWenKai-Regular", "仓耳今楷";

 亲测，是可以的

**Comment by UserZYF** [comment]
ok，之后更新会加上这个代码

**Comment by jinghu-moon** [comment]
那我关闭这个问题了。
