### ISSUE TITLE
如何给脑图添加彩色线条

### ISSUE THREAD

**Issue by huabingood** [UserZYF/zhang-light#4]
你好，感谢你开发的思源笔记主题。
请问如下的彩色线条的脑图是如何实现的？
![image](https://user-images.githubusercontent.com/20336634/156969955-bba2f599-3cbf-4d83-aebc-098bdb3e220d.png)

**Comment by UserZYF** [comment]
思源笔记二群，腾讯QQ号：155585856
群文件里边的挂件，名称 `cc-markmap 简单的思维导图挂件`
