### ISSUE TITLE
嵌入块中横排超级块的框线数量对不上

### ISSUE THREAD

**Issue by Tlonglan** [UserZYF/zhang-light#40]
如下图，实际上只横排了一次，但是在嵌入块中却显示为两个框
![image](https://user-images.githubusercontent.com/38731172/166098415-dd69fc40-f9b5-4de7-bbe8-f0cf370bd205.png)

**Comment by UserZYF** [comment]
这个方便把sy文件也发一下吗，我在思源笔记中看看怎么回事

**Comment by Tlonglan** [comment]
这是那个sy文件，麻烦看看
[20220421123822-rsq96pa.zip](https://github.com/UserZYF/zhang-light/files/8604002/20220421123822-rsq96pa.zip)

**Comment by UserZYF** [comment]
可以能因为嵌入块的缘故，所以多加了一层边框。右上角出现的那个是bug，升级到最新版就没有了
