### ISSUE TITLE
希望可以加强分割线的样式

### ISSUE THREAD

**Issue by Tlonglan** [UserZYF/zhang-light#43]
新版本的分割线好像太弱了，差点以为没有加分割线
下图的两行文字中间是有一条分割线的，但是好像跟方格子背景融到一起了，希望可以加粗或者加深一下~
![image](https://user-images.githubusercontent.com/38731172/167453017-f06067e1-d8c2-4b37-8554-5725f1898dbe.png)

**Comment by UserZYF** [comment]
嗯嗯，感谢反馈，下次更新会进行强调，暂时想法是换成渐变颜色
但不再是以前那种动态的了，
动态的会占用CPU

**Comment by Tlonglan** [comment]
渐变这个倒无所谓，说实话，之前那个动态分割线，在一堆静态内容里确实有一丢丢抢眼，去掉动态效果我觉得挺好的🤗
