### ISSUE TITLE
【Bug】已下载的主题点进详情后显示为未下载状态

### ISSUE THREAD

**Issue by Tlonglan** [UserZYF/zhang-light#44]
集市里已经下载了的主题，好像因为前面没有显示按钮，所以点进去之后被判定为“未下载”的状态了
![image](https://user-images.githubusercontent.com/38731172/167453462-c9e07b07-47ff-4546-8257-85a95a4d26ee.png)
![image](https://user-images.githubusercontent.com/38731172/167453512-98a81805-64ae-4eb0-9482-a25c678034b9.png)

另外，**不显示当前正在使用主题的按钮的特性，似乎容易跟未下载的主题混淆**，希望能重新考虑一下这个特性，或者，这也是一个小Bug？
> 右下角这个暗黑主题我并没有下载和使用，但是在外观上就和左上正在使用的Zhang-light主题一模一样
![image](https://user-images.githubusercontent.com/38731172/167453979-70a7092d-ac92-40fe-b72b-2792b3af7174.png)
![image](https://user-images.githubusercontent.com/38731172/167454038-47f4766c-1c7f-4580-bdc5-a200b7bfbf8c.png)

**Comment by wanghusw** [comment]
同样的问题，主题无法应用。

**Comment by UserZYF** [comment]
抱歉，因为更改了theme.json里边的主题名字，就成现在这样了。
需要把theme文件中所有包含zhang-light，Zhang-Light主题的文件夹全部删除
然后再重新从集市中下载，下次更新会在集市中进行说明
十分感谢反馈·~

**Comment by wanghusw** [comment]
> 同样的问题，主题无法应用。

不过在「外观」里面选择主题是可以应用的。
