### ISSUE TITLE
## 莫名灰色底色

### ISSUE THREAD

**Issue by Faith-YSQ** [UserZYF/zhang-light#45]
<img width="232" alt="Snipaste_2022-05-10_09-44-29" src="https://user-images.githubusercontent.com/66512309/167526018-a5d06a99-5387-4ba2-b7d2-09ea08004a41.png">
<img width="271" alt="Snipaste_2022-05-10_09-43-44" src="https://user-images.githubusercontent.com/66512309/167526031-63efef28-f6c4-4c40-bb0d-f9a8181762e9.png">
也不知道是不是bug，这里有些地方底色变灰色了

**Comment by UserZYF** [comment]
不知道动到什么了，确实是bug，下次更新修复，感谢反馈~

**Comment by aydove** [comment]
想问一下导图导出为pdf为什么会有一个灰点呢, 不知道大家有没有这种情况, 是我乱改css出问题了吗?另外想请问一下导出pdf为什么就不是仓耳今楷03-W04字体了呢?
![image](https://user-images.githubusercontent.com/24264863/168457257-ac237350-f4c5-4b01-acf9-5444ece4092d.png)

**Comment by UserZYF** [comment]
抱歉，这几天比较忙，刚回复
下次更新增加导出时保留字体，另外那个列表转导图的导图，我这里尝试了一下，是没有问题的
![Snipaste_2022-05-19_22-00-06](https://user-images.githubusercontent.com/38289979/169311861-b3514da6-96ef-40bc-9a0f-6a79bf39a0e9.png)

**Comment by UserZYF** [comment]
抱歉，这几天比较忙，刚回复，这些问题在下次更新修复，感谢反馈~
