### ISSUE TITLE
标题块折叠后标号错误

### ISSUE THREAD

**Issue by zllz4** [UserZYF/zhang-light#46]
![image](https://user-images.githubusercontent.com/38122008/168767358-9a110cb5-73b6-43c0-9d83-e89121f89db7.png)
如图，折叠了"大标题2”之后第三个标题的标号变成了"第二章"，本来应该是"第三章"
使用的是集市中显示为 v0.75 的版本

**Comment by UserZYF** [comment]
感谢反馈，下次更新修复

**Comment by zllz4** [comment]
woc秒回，老哥牛逼
