### ISSUE TITLE
链接为 FTP 目录时显示效果不理想

### ISSUE THREAD

**Issue by gagmeng** [UserZYF/zhang-light#47]
链接为 FTP 目录时显示效果不理想
![image](https://user-images.githubusercontent.com/13564117/168776937-2c853726-8440-4156-b699-9b31e8eb8be4.png)

**Comment by UserZYF** [comment]
跟字体有关，仓耳金楷字体在处理"\"符号时，后面会造成空格，可以换成那个什么鹭字体试试，具体在群里问问字体全称

**Comment by gagmeng** [comment]
用了霞鹭文楷字体后解决，多谢
