### ISSUE TITLE
你好，霞鹜文楷字体要如何生效？

### ISSUE THREAD

**Issue by wanghusw** [UserZYF/zhang-light#50]
霞鹜文楷的字体已经下载安装，但是并不生效。
另，仓耳今楷和霞鹜文楷两种字体在系统中只能装一种吗？还是说要怎么设置？

**Comment by UserZYF** [comment]
安装哪个哪个就生效，如果两个都安装了，生效的是前一个，那个文楷字体



---原始邮件---
发件人: "Hu ***@***.***&gt;
发送时间: 2022年5月25日(周三) 上午10:02
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [UserZYF/zhang-light] 你好，霞鹜文楷字体要如何生效？ (Issue #50)




 
霞鹜文楷的字体已经下载安装，但是并不生效。
 另，仓耳今楷和霞鹜文楷两种字体在系统中只能装一种吗？还是说要怎么设置？

**Comment by wanghusw** [comment]
`LXGWWenKai-Regular.ttf` 安装之后并不起作用……

**Comment by UserZYF** [comment]
重启一下思源笔记试试？这个字体名称和之前设置的代码一模一样，不应该不生效呀

---原始邮件---
发件人: "Hu ***@***.***&gt;
发送时间: 2022年5月25日(周三) 中午11:59
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [UserZYF/zhang-light] 你好，霞鹜文楷字体要如何生效？ (Issue #50)




 
LXGWWenKai-Regular.ttf 安装之后并不起作用……

**Comment by wanghusw** [comment]
仓耳字体一安装，重启一下立刻就生效了，但是霞鹜文楷是不行的……

**Comment by UserZYF** [comment]
是暗色还是亮色模式



---原始邮件---
发件人: "Hu ***@***.***&gt;
发送时间: 2022年5月25日(周三) 下午5:59
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [UserZYF/zhang-light] 你好，霞鹜文楷字体要如何生效？ (Issue #50)




 
仓耳字体一安装，重启一下立刻就生效了，但是霞鹜文楷是不行的……

**Comment by wanghusw** [comment]
亮色模式

**Comment by wanghusw** [comment]
呃，文楷字体就是不生效，无力……

**Comment by wanghusw** [comment]
我终于知道霞鹜文楷要怎么生效了，要在 `设置` 的 `编辑器` 里面修改，只要安装了霞鹜文楷，`字体` 设置那里选择就行了。该 Issues 我关闭了。
