### ISSUE TITLE
标题块转换为超级块后样式丢失

### ISSUE THREAD

**Issue by zllz4** [UserZYF/zhang-light#52]
https://user-images.githubusercontent.com/38122008/171201496-8fbda8c4-44d7-44f7-9bbf-1a1626bbc01f.mp4

如视频所示，转换为超级块之后原标题样式就没了

**Comment by zllz4** [comment]
![image](https://user-images.githubusercontent.com/38122008/171211604-9fa10c02-d04a-4351-9fc6-4e32422979cb.png)

另外问下按 `/` 出来的菜单栏怎么使用键盘选择”下一项“或者"右一项"? 按方向键好像没有用

**Comment by UserZYF** [comment]
感谢反馈，第一个是特意这么做的，但是时间久远，忘了当初为什么这么做了😂😂😂，之后几个版本，我再观察观察，不行再加上；第二个是因为这是用CSS分栏做到的，不是表格，只是将一列分栏显示，所以只有↑↓起作用，←→是不起作用的
