### ISSUE TITLE
问下怎样在文档树栏显示反链计数？

### ISSUE THREAD

**Issue by zllz4** [UserZYF/zhang-light#54]
daylight 主题，默认文档树右边会显示反链计数
![image](https://user-images.githubusercontent.com/38122008/180795043-e78ae39f-61bd-409d-89af-72b6a4f44aaa.png)
但是使用 zhang-light 好像没了，问下这个应该怎样可以显示出来？
![image](https://user-images.githubusercontent.com/38122008/180794890-65627ec8-2fa7-4c3c-8ccc-e84a0805bb83.png)

**Comment by UserZYF** [comment]
在主题文件夹里边，又有一个custom.css文件，里边有操作方法



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月25日(周一) 晚上10:00
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [UserZYF/zhang-light] 问下怎样在文档树栏显示反链计数？ (Issue #54)




 
daylight 主题，默认文档树右边会显示反链计数
 
 但是使用 zhang-light 好像没了，问下这个应该怎样可以显示出来？
