### ISSUE TITLE
引用块下划线异常

### ISSUE THREAD

**Issue by zllz4** [UserZYF/zhang-light#55]
![image](https://user-images.githubusercontent.com/38122008/188267706-5f3a4daa-e768-40c5-88d3-462412301d58.png)

引用块下划线似乎过于往上了，不清楚这是 bug 还是 feature？

**Comment by UserZYF** [comment]
之前版本更新导致的，下次更新修复



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月3日(周六) 晚上7:10
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [UserZYF/zhang-light] 引用块下划线异常 (Issue #55)




 

 
引用块下划线似乎过于往上了，不清楚这是 bug 还是 feature？
