### ISSUE TITLE
页面背景格子

### ISSUE THREAD

**Issue by bahayonghang** [UserZYF/zhang-light#6]
页面背景格子去掉了吗，我发现的更新后我的背景没有格子了，更新日志也没有找到相关说明

**Comment by UserZYF** [comment]
没有去掉，有些朋友反映格子背景颜色深，我又给调淡了一些
翻转一下电脑屏幕，看有没有，如果觉得不明显，我下次更新给弄深一些

**Comment by bahayonghang** [comment]
抱歉，应该是屏幕色域的问题，买的显示屏色域有问题，看不清楚，笔记本电脑屏没问题，谢谢回复
