### ISSUE TITLE
背景色字体效果全部变成了背景色+黑色字体

### ISSUE THREAD

**Issue by zllz4** [UserZYF/zhang-light#61]
![image](https://user-images.githubusercontent.com/38122008/193512337-2c0c7a1c-bb5a-4a61-b7cc-7395b3efed8b.png)

如图，所有的绿底绿字、红底红字、橙底橙字效果全都变成了绿底黑字、红底黑字、橙底黑字

**Comment by UserZYF** [comment]
感谢反馈，下个版本修复



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月3日(周一) 下午2:18
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [UserZYF/zhang-light] 背景色字体效果全部变成了背景色+黑色字体 (Issue #61)




 

 
如果，所有的绿底绿字、红底红字、橙底橙字效果全都变成了绿底黑字、红底黑字、橙底黑字
