### ISSUE TITLE
列表转看板，点击以后没有反应

### ISSUE THREAD

**Issue by AugustTuan** [UserZYF/zhang-light#62]
是对列表的长度有什么限制之类的吗？(●'◡'●)
![image](https://user-images.githubusercontent.com/37429029/194893595-21dfda7e-ca2f-4e43-a0de-551bc4368af0.png)

**Comment by UserZYF** [comment]
因为没有加这个功能，只是个空的按钮，下次更新加上



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月10日(周一) 晚上10:47
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [UserZYF/zhang-light] 列表转看板，点击以后没有反应 (Issue #62)




 
是对列表的长度有什么限制之类的吗？(●'◡'●)

**Comment by AugustTuan** [comment]
好的(❁´◡`❁)

**Comment by AugustTuan** [comment]
对了，我用了其他主题的看板模式，发现一个很头疼的问题，就是拖动条放在了底部，导致左右拖动非常不方便。
希望看板模式的横向拖动条可以出现在顶部
[列表转看板以后，看板的左右拖动条能否放在顶部 · Issue #7 · royc01/salt](https://github.com/royc01/salt/issues/7)
