### ISSUE TITLE
感谢作者！一些建议

### ISSUE THREAD

**Issue by PsyAbyss** [UserZYF/zhang-light#7]
**1、列表转表格很赞，但是转换完表格右边界与文字距离太近**，如：
![微信图片_20220309140959](https://user-images.githubusercontent.com/74729337/157382834-0c4b97bc-e135-4991-a9ef-d1587a607f30.png)
希望可以优化一下。

----
**2、行内代码颜色有点太浅**，如：
![微信截图_20220309141203](https://user-images.githubusercontent.com/74729337/157383083-7d45f9e9-c84e-49e3-a637-2fe40e128ff2.png)
希望可以换成更醒目的颜色或者加深字体。

----
**3、行内有许多小图片时，图片的阴影影响阅读体验**，如：
![微信截图_20220309141450](https://user-images.githubusercontent.com/74729337/157383372-60396d10-7d2c-467e-87b5-a49cfc4efa31.png)
希望可以修改为行内图片不加阴影，另起一行的图片才加阴影？如果不好实现的话能不能在文档的自定义属性中增加一项“图片无阴影”。

**Comment by UserZYF** [comment]
感谢反馈，都是十分中肯的建议，应该都能实现。我今天晚上修改修改，争取今天晚上更新
