### ISSUE TITLE
【Bug】版本0.4，使用模板关键字搜索时出现多一个有效的空白选项

### ISSUE THREAD

**Issue by Tlonglan** [UserZYF/zhang-light#8]
![image](https://user-images.githubusercontent.com/38731172/157483638-20338b97-551d-4b80-85d1-07418f8ee489.png)

如上图所示，点击模板之后，搜索关键字，选项里会多出一个相同的空白的选项，点击可以正常使用，
> 版本：0.4

**Comment by UserZYF** [comment]
ok，感谢反馈，我试试看能不能修改

**Comment by UserZYF** [comment]
已经修改审核通过了，等着今晚集市的更新吧

**Comment by Tlonglan** [comment]
好耶！辛苦啦~

**Comment by Tlonglan** [comment]
更新的是0.41吗？好像还是有这个问题噢

**Comment by UserZYF** [comment]
上架了一天了，还没到集市里边...
可以直接在我的GitHub下载，最新版本是0.5，更新了网站链接前面的icon

**Comment by Tlonglan** [comment]
噢噢好~ 我去看看
